HELLO = "привет"
HELP = "я тебе что, консультант в пятерочке что ли"
DEFAULT = "используй команды"
REG_START = "отлично, регистрация\n\nпридумай пароль:"
CREDENTIALS_LOGIN = "твой логин: {}"
CREDENTIALS = CREDENTIALS_LOGIN + "\n" \
              "твой пароль: {}"
REG_SUCCESS = "регистрация пройдена"
ACCOUNT = "настройки аккаунта"
ACCOUNT_LOGIN_CHANGE = "новый логин: "
ACCOUNT_LOGIN_CHANGE_SUCCESS = "логин изменён"
ACCOUNT_PASSWORD_CHANGE = "новый пароль: "
ACCOUNT_PASSWORD_CHANGE_SUCCESS = "пароль изменён"
ACCOUNT_LOGIN_CHANGE_LOGIN_TAKEN = "логин занят, придумай другой"
ACCOUNT_LOGIN_CHANGE_WRONG_CHARACTERS = "используй только английские буквы"
ACCOUNT_LOGIN_CHANGE_LOGIN_TOO_LONG = "не больше 100 символов, давай снова"
ACCOUNT_LOGIN_CHANGE_LOGIN_SAME = "это и так твой логин"
