HELLO = "привет"
HELP = "there is no help yet"
DEFAULT = "используй команды"
REG_START = "отлично, регистрация\n\nпридумай пароль:"
CREDENTIALS_LOGIN = "твой логин: {}"
CREDENTIALS = CREDENTIALS_LOGIN + "\n" \
              "твой пароль: {}"
REG_SUCCESS = "регистрация пройдена"
ACCOUNT = "настройки аккаунта"
ACCOUNT_LOGIN_CHANGE = "новый логин: "
ACCOUNT_LOGIN_CHANGE_SUCCESS = "логин изменён"
ACCOUNT_PASSWORD_CHANGE = "новый пароль: "
ACCOUNT_PASSWORD_CHANGE_SUCCESS = "пароль изменён"
